name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Unzip ZIP project
        run: |
          unzip "*.zip" -d project

      - name: Build APK
        run: |
          cd project
          flutter pub get
          flutter build apk --release

      - name: Send APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -F document=@project/build/app/outputs/flutter-apk/app-release.apk \
               "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?chat_id=${TELEGRAM_CHAT_ID}"
